---

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Ensure dependencies for Deb
  block:
    - name: Add Ceph repo keyring
      apt_key:
        url: "{{ ceph_repo_sig }}"

    - name: Add Ceph repo
      apt_repository:
        repo: "deb https://download.ceph.com/debian-{{ ceph_release }}/ {{ ansible_distribution_release }} main"

    - name: Install base software set
      apt:
        name: "{{ software_packages }}"
        state: present
        autoclean: yes
      changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy ntp config
  copy:
    src: "{{ role_path }}/files/ntp.conf"
    dest: /etc/ntp.conf
  notify:
    - Restart ntpd

- name: Install pip
  apt:
    name: "python{{ '' if ansible_python_version.startswith('2') else '3' }}-pip"
    state: present
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install hvac for Hashicorp Vault support
  pip:
    name: hvac
    state: present
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'